### ISSUE TITLE
Error: Type 'MaxLengthEnforcement' not found.

### ISSUE THREAD

**Issue by czw410935195** [moesama/megami#1]
Flutter Channel stable, 1.22.6,
Dart version 2.10.5

../../../.pub-cache/hosted/localhost%25588889/megami-0.0.1/lib/style_exts.dart:210:11: Error: Type 'MaxLengthEnforcement' not found.
          MaxLengthEnforcement maxLengthEnforcement,
          ^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/localhost%25588889/megami-0.0.1/lib/megami_utils.dart:62:64: Error: The getter 'firstOrNull' isn't defined for the class 'Iterable<UriTerm>'.
 - 'Iterable' is from 'dart:core'.
 - 'UriTerm' is from 'package:megami/css/visitor.dart' ('../../../.pub-cache/hosted/localhost%25588889/megami-0.0.1/lib/css/visitor.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'firstOrNull'.
          expression.expressions.reversed.whereType<UriTerm>().firstOrNull;

**Comment by moesama** [comment]
This issue is caused by the channel of flutter sdk, I used master channel, now I change to stable channel.
